// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugtpogaertobgbqvvjxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVndHBvZ2FlcnRvYmdicXZ2anh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzQ4MjgsImV4cCI6MjA2NTc1MDgyOH0.VmiGssSnkIdSAiOSH-CMGn7UNQJHL2nYtBTIx2Pdnls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);